// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servidor_PI.Data;

#nullable disable

namespace Servidor_PI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Servidor_PI.Models.Campanha", b =>
                {
                    b.Property<int>("cd_campanha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("fim")
                        .HasColumnType("DATE");

                    b.Property<DateTime?>("inicio")
                        .HasColumnType("DATE");

                    b.Property<decimal?>("meta_arrecadacao")
                        .HasColumnType("REAL");

                    b.Property<string>("nome_campanha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("cd_campanha");

                    b.ToTable("Campanha", (string)null);
                });

            modelBuilder.Entity("Servidor_PI.Models.Doacao", b =>
                {
                    b.Property<int>("cd_doacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cd_campanha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cd_cliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("forma_arrecadacao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_doacao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("status_arrecadacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("tipo_doacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("cd_doacao");

                    b.HasIndex("cd_campanha");

                    b.HasIndex("cd_cliente");

                    b.HasIndex("status_arrecadacao")
                        .HasDatabaseName("idx_doacao_status");

                    b.ToTable("Doacao", (string)null);
                });

            modelBuilder.Entity("Servidor_PI.Models.Noticias", b =>
                {
                    b.Property<int>("cd_noticias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("autor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("cd_campanha")
                        .HasColumnType("INTEGER");

                    b.Property<string>("conteudo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("data_noticia")
                        .HasColumnType("DATE");

                    b.Property<string>("titulo_noticia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("cd_noticias");

                    b.HasIndex("cd_campanha");

                    b.HasIndex("data_noticia")
                        .HasDatabaseName("idx_noticias_data");

                    b.ToTable("Noticias", (string)null);
                });

            modelBuilder.Entity("Servidor_PI.Models.Relatorio", b =>
                {
                    b.Property<int>("cd_relatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("cd_campanha")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data_relatorio")
                        .HasColumnType("DATE");

                    b.Property<string>("tipo_relatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("valor_gasto")
                        .HasColumnType("REAL");

                    b.HasKey("cd_relatorio");

                    b.HasIndex("cd_campanha");

                    b.ToTable("Relatorio", (string)null);
                });

            modelBuilder.Entity("Servidor_PI.Models.Usuario", b =>
                {
                    b.Property<int>("cd_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("cpf")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_completo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("nome_usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("cd_cliente");

                    b.HasIndex("cpf")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_cpf");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_email");

                    b.HasIndex("nome_usuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Servidor_PI.Models.Doacao", b =>
                {
                    b.HasOne("Servidor_PI.Models.Campanha", "Campanha")
                        .WithMany("Doacoes")
                        .HasForeignKey("cd_campanha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Servidor_PI.Models.Usuario", "Usuario")
                        .WithMany("Doacoes")
                        .HasForeignKey("cd_cliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Servidor_PI.Models.Noticias", b =>
                {
                    b.HasOne("Servidor_PI.Models.Campanha", "Campanha")
                        .WithMany("Noticias")
                        .HasForeignKey("cd_campanha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Servidor_PI.Models.Relatorio", b =>
                {
                    b.HasOne("Servidor_PI.Models.Campanha", "Campanha")
                        .WithMany("Relatorios")
                        .HasForeignKey("cd_campanha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("Servidor_PI.Models.Campanha", b =>
                {
                    b.Navigation("Doacoes");

                    b.Navigation("Noticias");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("Servidor_PI.Models.Usuario", b =>
                {
                    b.Navigation("Doacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
